### ISSUE TITLE
There is no source code

### ISSUE THREAD

**Issue by IAmStoxe** [mirinsoft/spydish#1]
This app should not be used until the author @Belim decides to release the code. Github is not a release avenue for precompiled binaries. Relese the code or find another community. This is not safe.

**Comment by Belim** [comment]
Nobody forces you to use my software. I decide which community i use and i certainly don't violate the Github guidelines just because the code is not open.
Im already distributing the software on my own sites for years and i do it all for free. I'm using GitHub for hosting and issues tracking.

Why do you feel attacked. If you have a problem with my software, then please make a detour around it but such comments are more than just embarrassing.

**Comment by IAmStoxe** [comment]
GitHub is for open source software; plain and simple. Nobody should ever
trust a closed-source product from an independent developer that touches
group policy settings in my opinion. I hope it is obvious what a gigantic
security concern that is.

And as you mentioned the GitHub rules, there is nothing preventing me from
voicing my concerns within "issues".

I feel no such embarrassment.

**Comment by Belim** [comment]
You say my software is NOT safe just because it's closed. What about Github itself? Or Windows? Open source? No!

I'm not a for-profit company and keep my head above water with donations and one, two ads on my website and you come in here and you tell me my code isn't safe .That annoys but It's all good. Thanks for your comment and I'm NOT completely closed to open source. Wait and see approach
